### ISSUE TITLE
Bug: Crashes when choosing any item from the drawer

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [HiFIi/ToolbarMenudrawer-2.0#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object reference
                                                                     at com.kyler.tbmd2.ToolbarMenudrawer.onNavDrawerItemClicked(ToolbarMenudrawer.java:435)
                                                                     at com.kyler.tbmd2.ToolbarMenudrawer.access$300(ToolbarMenudrawer.java:53)
                                                                     at com.kyler.tbmd2.ToolbarMenudrawer$7.onClick(ToolbarMenudrawer.java:591)
                                                                     at android.view.View.performClick(View.java:5198)
                                                                     at android.view.View$PerformClick.run(View.java:21147)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by HiFIi** [comment]
im probably never going to work on this again, but thank you for the report. if i ever find myself wanting to rehash this i will def. be doing it from scratch because I have learned and grown so much.
- Kyler

**Comment by AndroidDeveloperLB** [comment]
Why is it closed? Was it fixed?

**Comment by HiFIi** [comment]
my bad :p
